### PR TITLE
A Link to Quantum: a collection of video-games

### PR DESCRIPTION
**Pull request by msohaibalam**
To play the games, you must have the following installed:
- pygame (www.pygame.org)
- blender (https://www.blender.org)
(as well as pyquil)

For instructions on how to make pyquil work with blender, see "readme_install.txt".

Run "pythonw overworld.py" in the folder grove/grove/link_to_quantum_game. (NOTE the use of "pythonw" instead of the usual "python")

There are 4 games embedded inside the meta-game "Overworld", each of which can (currently) be played only once in each session of "Overworld". To play :-
- "Quantum Block-out", move to the top-most cell in the middle;
- "Quantum Darts", move to the bottom-most cell in the middle;
- "Meyer Penny Classical/Quantum Game", move to the left-most cell in the middle;
- "Meyer Penny Quantum/Quantum Game", move to the right-most cell in the middle
(the classical/classical and quantum/classical versions of the Meyer penny game can separately be played by calling "pythonw meyer_classical_classical_game.py" and "meyer_quantum_classical_game.py" respectively.)

### CODE REVIEW

**Comment by willzeng** [comment]
@msohaibalam Thanks for the submission! We chatted a bit internally and think that these games would likely be best in their own repository rather than merging into grove. We'd love to link to them though on our website etc.

I'm putting together a list of Forest projects right now so if you do make a separate repo/link then let me know and I can add these games.

**Comment by ampolloreno** [comment]
@msohaibalam, @willzeng Looks like cool stuff! 

It does seem like these should live somewhere else, and it looks like there was a repo made by @msohaibalam  on his account.

Are we all agreed that we'll close this PR then?

**Comment by msohaibalam** [comment]
@ampolloreno Thanks, and yes! I had earlier shared the link to the stand-alone repo with @willzeng elsewhere, but didn't realize I needed to close this PR. Closing it now.

**Comment by willzeng** [comment]
@msohaibalam would great to add the games repo to this list of Forest software

https://github.com/rigetticomputing/forest-software/blob/master/README.md

**Comment by msohaibalam** [comment]
@willzeng Done! Just created a PR there.

**Pull request closed without merging**
