### PR TITLE
Generate arbitrary complex state

### PR DESCRIPTION
**Pull request by harleypatton**
Wrote a module to encode arbitrary vectors into  the wavefunction of a quantum state.

### CODE REVIEW

**Comment by harleypatton** [comment]
pytest is currently marked to skip because of #33

**Comment by harleypatton** [comment]
@joelin0 found a way to do this without a defgate! See #41

**Comment by willzeng** [comment]
@harleypatton @joelin0 Is this PR now superseded by #41?

**Comment by joelin0** [comment]
@willzeng I think so, I'll let @harleypatton check #41 over again to make sure though.

**Comment by joelin0** [comment]
@willzeng I think it was decided that this module is still useful for making the matrix itself (independent of the Program), so @harleypatton may modify this PR and keep it.

**Comment by harleypatton** [comment]
Content from this PR has been added to #41. Closing down

**Pull request closed without merging**
