### PR TITLE
Feature/order finding

### PR DESCRIPTION
**Pull request by harleypatton**
Aaron and I implemented order finding of modular exponentials, and used it to implement Shor's. Tests coming soon

### CODE REVIEW

**Comment by vontell** [comment]
Todo:
[ ] Add tests for order finding
[ ] Migrate Java tests to Python for Shor's algorithm
[ ] Incorporate better primality checking, such as ECPP

**Comment by vontell** [comment]
Issue #33 may be relevant to this PR. Also, I have added a new dependency of elliptical curve primality checking, so that may case the breaking check in semaphore. Any idea how to install this correctly?

**Comment by willzeng** [comment]
@vontell It could be a few things. I don't quite have fast enough internet while travelling to disambiguate them.

(1) did you add the new dependencies to requirements.txt?

(2) semaphore currently builds against the most recent version of pyQuil. Given that pyQuil was recently updated to 1.0.0 on pypi this may mean you need to do some upgrading of this branch.

**Comment by vontell** [comment]
Ah looks like the primality check dependency is not the issue; the build failed due to the fact that the forest object cannot be found, which must be related to the new pyQuil changes. I will work on fixing these.

**Comment by ncrubin** [comment]
What's the status of this PR?

**Comment by vontell** [comment]
Should be good to go; it's just missing tests for `ordering_finding.py`, which I was hoping to do once there is some discussion regarding issue #33. 

Also it should be noted that order_finding does not always obtain the correct result due to interesting edge cases, but these will be fixed along with the added test. These edge cases, however, do not affect shor.py, as it can detect these errors.

Other than that, feel free to review and merge.

**Comment by jotterbach** [comment]
@vontell @harleypatton Thanks for your hard work on this. Can you comment what remains to be done to bring this over the finish line? What's the test coverage ratio?

**Comment by jotterbach** [comment]
closing this out due to inactivity

**Pull request closed without merging**
